#معايا داتا لشركه عاوز اعرف انهي بيانات للموظفين هي الي بتأثر علي انتجهم يعني لو انا كمستثمر عاوز اشتغل او اشتري واحده فيهم 
#هشتري انهي هشوف الي بتصرف علي الموظفين ولا الي بتصرف علي الموارد ولا الاتنين ..مثلا فهعمل مودل يشوف انهي 
#احلي شركه

# **Multiple linear regression**

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
dataset=pd.read_csv('50_Startups.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,4].values


In [11]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

# **Encoding categorical data**

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()

In [13]:
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

#Avoiding damy variable trap لما عملت الداتا فوق اتحولت ل 0و1 فعلشان كدا ممكن تعمل 
#damy
#فهعمل كود يحاول يميز بين ال0 و 1 علشان ماتيلغبطش 

In [4]:
X=X[:,1:]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# *fiting Multiple linear regression to the training set*

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# **predicting the test set results**

In [10]:
y_pred=regressor.predict(X_test)
#y_pred_test=regressor.predict(X_train)

In [11]:
y_pred

array([108087.40943475,  94075.52935037, 103684.13111554, 109115.49885826,
       103344.82807584, 119826.12211671,  94325.09783199, 130700.8478805 ,
       108898.78755726, 103344.82807584])

In [12]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [13]:
from sklearn.metrics import mean_squared_error 
print("The Mean Squared Error is- {}".format(mean_squared_error(y_test, y_pred))) 

The Mean Squared Error is- 1846130824.0073693


# to know the p ..to remove the right colomn

In [15]:
import statsmodels.api as sm

X=np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)

X_opt=X[:,[0,1,2,3,4,5]]
regressor_OLS =sm.OLS(endog=y,exog=X_opt).fit()

regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     2.244
Date:                Sat, 23 Oct 2021   Prob (F-statistic):             0.0665
Time:                        23:28:38   Log-Likelihood:                -594.98
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      44   BIC:                             1213.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.178e+05   5659.867     20.808      0.000    1.06e+05    1.29e+05
x1         -8.209e+04   3.84e+04     -2.139      0.038   -1.59e+05   -4730.369
x2         -5.284e+04   3.84e+04     -1.377      0.176    -1.3e+05    2.45e+04
x3         -6.828e+04   3.84e+04     -1.779      0.082   -1.46e+05    9086.971
x4         -4.801e+04   3.84e+04     -1.251      0.218   -1.25e+05    2.94e+04
x5         -3.654e+04   3.84e+04     -0.952      0.346   -1.14e+05    4.08e+04
==============================================================================
Omnibus:                        1.590   Durbin-Watson:                   0.512
Prob(Omnibus):                  0.452   Jarque-Bera (JB):                0.795
Skew:                          -0.059   Prob(JB):                        0.672
Kurtosis:                       3.606   Cond. No.                         7.47
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
X_opt=X[:,[0,1,2,3,4]]
regressor_OLS =sm.OLS(endog=y,exog=X_opt).fit()

regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.187
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     2.584
Date:                Sat, 23 Oct 2021   Prob (F-statistic):             0.0496
Time:                        23:28:38   Log-Likelihood:                -595.48
No. Observations:                  50   AIC:                             1201.
Df Residuals:                      45   BIC:                             1211.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.17e+05   5592.160     20.917      0.000    1.06e+05    1.28e+05
x1          -8.13e+04   3.83e+04     -2.121      0.039   -1.59e+05   -4083.603
x2         -5.205e+04   3.83e+04     -1.358      0.181   -1.29e+05    2.52e+04
x3         -6.748e+04   3.83e+04     -1.760      0.085   -1.45e+05    9733.737
x4         -4.721e+04   3.83e+04     -1.232      0.225   -1.24e+05       3e+04
==============================================================================
Omnibus:                        1.208   Durbin-Watson:                   0.460
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.481
Skew:                          -0.012   Prob(JB):                        0.786
Kurtosis:                       3.480   Cond. No.                         7.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
import statsmodels.formula.api as sm
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x
 
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)
Backward Elimination with p-values and Adjusted R Squared:
import statsmodels.formula.api as sm
def backwardElimination(x, SL):
    numVars = len(x[0])
    temp = np.zeros((50,6)).astype(int)
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if maxVar > SL:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    temp[:,j] = x[:, j]
                    x = np.delete(x, j, 1)
                    tmp_regressor = sm.OLS(y, x).fit()
                    adjR_after = tmp_regressor.rsquared_adj.astype(float)
                    if (adjR_before >= adjR_after):
                        x_rollback = np.hstack((x, temp[:,[0,j]]))
                        x_rollback = np.delete(x_rollback, j, 1)
                        print (regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue
    regressor_OLS.summary()
    return x
 
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)


SyntaxError: invalid character in identifier (<ipython-input-17-5b51ba1e315b>, line 3)